// Generated by scripts/domain-packages.mjs. Do not edit.
import type { DomainRendererHost } from '@sciforge/domain-sdk/host'
import { defineInstalledRendererDomainEntrySet } from '@sciforge/domain-sdk/renderer'
import { createDomainRendererEntry as createDomainRendererEntry0 } from '@sciforge/domain-anchored-comments/renderer'
import { createDomainRendererEntry as createDomainRendererEntry1 } from '@sciforge/domain-browser-preview/renderer'
import { createDomainRendererEntry as createDomainRendererEntry2 } from '@sciforge/domain-change-inspector/renderer'
import { createDomainRendererEntry as createDomainRendererEntry3 } from '@sciforge/domain-content-space/renderer'
import { createDomainRendererEntry as createDomainRendererEntry4 } from '@sciforge/domain-create-loop/renderer'
import { createDomainRendererEntry as createDomainRendererEntry5 } from '@sciforge/domain-evidence-dag/renderer'
import { createDomainRendererEntry as createDomainRendererEntry6 } from '@sciforge/domain-git-checkpoints/renderer'
import { createDomainRendererEntry as createDomainRendererEntry7 } from '@sciforge/domain-identity-access/renderer'
import { createDomainRendererEntry as createDomainRendererEntry8 } from '@sciforge/domain-life-science-preview/renderer'
import { createDomainRendererEntry as createDomainRendererEntry9 } from '@sciforge/domain-paper-radar/renderer'
import { createDomainRendererEntry as createDomainRendererEntry10 } from '@sciforge/domain-project-dag/renderer'
import { createDomainRendererEntry as createDomainRendererEntry11 } from '@sciforge/domain-remote-ssh/renderer'
import { createDomainRendererEntry as createDomainRendererEntry12 } from '@sciforge/domain-terminal/renderer'
import { createDomainRendererEntry as createDomainRendererEntry13 } from '@sciforge/domain-visual-review/renderer'
import { installedDomainPackages } from '@shared/installed-domain-packages'
import type { VisibleContextComponentSnapshot } from '@shared/visible-context'
import { rendererCapabilityClient } from '../lib/capability-client'
import { openSafeExternalUrl } from '../lib/open-external'
import {
  inspectRegisteredVisibleContextTargetAt,
  inspectRegisteredVisibleContextTextSelection,
  registerVisibleContextComponent,
  registerVisibleContextVisualTarget
} from '../lib/visible-context'
import { createDomainRendererApplicationHost } from './application-overlay-slot'
import { domainRendererNavigationHost } from './domain-renderer-navigation'

function domainHost(ownerId: string): DomainRendererHost {
  return {
    capabilityInvoker: rendererCapabilityClient,
    openExternal: async (url) => {
      await openSafeExternalUrl(url)
    },
    application: createDomainRendererApplicationHost(ownerId),
    fileTransfers: {
      pickUploadSource: (input) => window.sciforge.pickUploadTransfer(input),
      pickDownloadDestination: (input) => window.sciforge.pickDownloadTransfer(input)
    },
    workspace: {
      pickFile: (request) => window.sciforge.pickFile(request),
      openRemoteSession: async (input) => {
        await window.sciforge.remoteWorkspace.attach(input)
      }
    },
    ...domainRendererNavigationHost,
    visibleContext: {
      registerComponent: (component) => registerVisibleContextComponent(
        component as VisibleContextComponentSnapshot
      ),
      registerVisualTarget: ({ element, ...input }) => registerVisibleContextVisualTarget({
        ...input,
        ...(element ? { element: element as () => Element | null } : {})
      }),
      inspectRegisteredTargetAt: inspectRegisteredVisibleContextTargetAt,
      inspectRegisteredTextSelection: inspectRegisteredVisibleContextTextSelection
    }
  }
}

export const installedRendererDomainEntrySet = defineInstalledRendererDomainEntrySet<unknown>(
  installedDomainPackages,
  [
    createDomainRendererEntry0(domainHost('sciforge.anchored-comments')),
    createDomainRendererEntry1(domainHost('sciforge.browser-preview')),
    createDomainRendererEntry2(domainHost('sciforge.change-inspector')),
    createDomainRendererEntry3(domainHost('sciforge.content-space')),
    createDomainRendererEntry4(domainHost('sciforge.create-loop')),
    createDomainRendererEntry5(domainHost('sciforge.evidence-dag')),
    createDomainRendererEntry6(domainHost('sciforge.git-checkpoints')),
    createDomainRendererEntry7(domainHost('sciforge.identity-access')),
    createDomainRendererEntry8(domainHost('sciforge.life-science-preview')),
    createDomainRendererEntry9(domainHost('sciforge.paper-radar')),
    createDomainRendererEntry10(domainHost('sciforge.project-dag')),
    createDomainRendererEntry11(domainHost('sciforge.remote-ssh')),
    createDomainRendererEntry12(domainHost('sciforge.terminal')),
    createDomainRendererEntry13(domainHost('sciforge.visual-review'))
  ]
)
